#spring.application.name=careerconnect-backend

spring.application.name=careerconnet-backend

spring.datasource.url=jdbc:mysql://localhost:3306/careerconnect
spring.datasource.username=root
spring.datasource.password=sree4154

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secretKey=mysecretekeymysecretekeymysecretekey12
jwt.expiration=3600000

server.port=8080